import "./globals.css";
import { UserProvider } from "@/context/userContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={` coolvetica`}>{children}</body>
      </UserProvider>
    </html>
  );
}
